### ISSUE TITLE
Support for Craft v4?

### ISSUE THREAD

**Issue by lmcnearney** [c10d-dev/craft-hcaptcha#2]
Do you plan to provide a new release with support for Craft v4?

**Comment by c10d-dev** [comment]
Yes, I'll try to look into it in the next few days.
Thanks for bringing it up!

**Comment by c10d-dev** [comment]
It should be working now!
Could you test it and tell if everything's ok?

**Comment by lmcnearney** [comment]
Thanks, will test it next week and provide feedback!

**Comment by lmcnearney** [comment]
I did some quick testing and ran into a couple of issues:

- The new `{{%crafthcaptcha_logs}}` table wasn't created when upgrading from version `1.2.0` to `2.0.0` as part of the overall Craft v4 upgrade. I'm not sure if this is my fault as I just followed the Craft upgrade guide and had manually changed all of the various plugin versions in `composer.json`. I went ahead re-installed the plugin which created the appropriate table.
- The `verify($data)` method always returns false even though the captcha is successfully solved. I debugged the code and it appears as part of commit 9436e515 that you now check that the `hostname` property matches the current request's hostname. This doesn't work on my local environment (likely because it resolves to localhost) and the hCaptcha documentation recommends not checking or relying on that property:

  https://docs.hcaptcha.com/#verify-the-user-response-server-side

  > Please also note that the hostname field is derived from the user's browser, and should not be used for authentication of any kind; it is primarily useful as a statistical metric. Additionally, in the event that your site experiences unusually high challenge traffic, the hostname field may be returned as "not-provided" rather than the usual value; all other fields will return their normal values.

  I would remove that check or make it optional through a config.

Assuming that's fixed, it looks like everything should work.

**Comment by c10d-dev** [comment]
Thank you for this detailed feedback, awesome!

On the first point, I need to verify and understand how Craft handles migrations but it should not impact the validation of the captcha.
For the second point, I just removed the check on the `hostname` for now, as recommended in the hcaptcha documentation.

I'll close this issue, feel free to reopen if you find something else!
