### ISSUE TITLE
Table missing after upgrading

### ISSUE THREAD

**Issue by codyjames** [c10d-dev/craft-hcaptcha#3]
Hey there!
I'm getting an error that the table `crafthcaptcha_logs` doesn't exist. Looking at the code it looks like the table is added in the Install migration – which I don't think works for folks who had already had the plugin installed.

Any ideas?
Let me know.
Thanks!

**Comment by c10d-dev** [comment]
Hello,
Are you updating to Craft 3 or Craft 4 ?
From which version of the plugin to which version ?
Did you tried to uninstall/reinstall the plugin ?
Thanks!

**Comment by codyjames** [comment]
I guess I'm just trying to point out that you put the table creation in the install migration instead of a migration that would apply to folks who are _upgrading_.

I was able to get it working by uninstalling and reinstalling but that's not super ideal. It makes it so folks who are upgrading have to troubleshoot this each time it happens.

No biggie. Love the plugin, btw!

**Comment by therealpecus** [comment]
@c10d-dev I don't think this issue should be closed. Upgrading to the latest 1.2.1 version of the plugin disabled it from working due to the log table missing. This should be fixed, as suggested, by updating the logic of when the migration that checks and creates the utility table runs.

**Comment by johnvanhulsen** [comment]
I've got the same issue. Also after disabling and enabling.

**Comment by johnvanhulsen** [comment]
Based on the code. When you have the same issue; This Create table will work

```
CREATE TABLE `crafthcaptcha_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` varchar(36) NOT NULL,
  `siteId` int(11) NOT NULL,
  `success` tinyint(1) NOT NULL DEFAULT '0',
  `requestUrl` mediumtext,
  `requestBody` longtext,
  `captchaJson` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
