### ISSUE TITLE
Unable to run migrations to install plugin

### ISSUE THREAD

**Issue by stuible** [c10d-dev/craft-hcaptcha#5]
In development I was able to this plugin but upon deploying to docker, the migrations seem unable to run when applying the configuration changes
```
Installing plugin "craft-hcaptcha" ... error: An error occurred while executing the "c10d\crafthcaptcha\migrations\Install migration: SQLSTATE[42883]: Undefined function: 7 ERROR:  function requesturl(integer) does not exist at character 82
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
The SQL being executed was: CREATE INDEX "idx_qpblxowlcijjgpzryizxuskayczhpvwffswp" ON "crafthcaptcha_logs" (requestUrl(40))
Aborting config apply process

```

Installing from scratch does not seem to trigger this error.  Anything I can try to debug this issue?

**Comment by c10d-dev** [comment]
Hello,
This seems weird.
What is your Craft version and your database type (mysql, pgsql,...) and the database version ?
Thanks

**Comment by stuible** [comment]
I am running:
PostgreSQL v13.9
Craft CMS v4.3.6.1

**Comment by stuible** [comment]
Is there any other info I can provide that could help resolve this?

**Comment by c10d-dev** [comment]
Sorry for the delay, I don't have much time to look into this.

But I think I may have a solution, so I'll let you know!

**Comment by stuible** [comment]
Absolutely no problem, I appreciate the plugin and all the time you've put into developing it.  Let me know if there's anything you want me to test!

**Comment by c10d-dev** [comment]
Thank you!

Could you try with the new v2.0.2 I just released?

Thanks again, let me know if it fixed the bug for you!

**Comment by stuible** [comment]
That fixed it!

Thanks a bunch :)
